/*BAI1.1*/
select MA_NVIEN,MADA,STT,
 CAST (THOIGIAN AS decimal(5,1)) AS 'THOI GIAN' FROM PHANCONG;

 select MA_NVIEN,MADA,STT,
 CONVERT ( decimal(5,1),THOIGIAN) AS 'THOI GIAN' FROM PHANCONG;
 /*BAI1.2*/
 DECLARE @THONGKE TABLE (MADA INT , THOIGIAN FLOAT);
 INSERT INTO @THONGKE
 SELECT MADA, SUM(THOIGIAN) AS'TONG THOI GIAN'
 FROM PHANCONG
 GROUP BY MADA;
 SELECT TENDEAN, CAST(THOIGIAN AS VARCHAR(15)) AS 'TONGTHOIGIAN' 
 FROM @THONGKE A INNER JOIN DEAN B ON A.MADA =B.MADA;
 
 SELECT TENDEAN, CONVERT( VARCHAR(15),THOIGIAN) AS 'TONGTHOIGIAN' 
 FROM @THONGKE A INNER JOIN DEAN B ON A.MADA =B.MADA;
 
 SELECT TENDEAN, CAST(THOIGIAN AS DECIMAL(5,2)) AS 'TONGTHOIGIAN' 
 FROM @THONGKE A INNER JOIN DEAN B ON A.MADA =B.MADA;
 
 SELECT TENDEAN, CONVERT(DECIMAL(5,2),THOIGIAN) AS 'TONGTHOIGIAN' 
 FROM @THONGKE A INNER JOIN DEAN B ON A.MADA =B.MADA;
 /*BAI1.3*/
 SELECT PHG,CONVERT(DECIMAL(15,2), AVG (LUONG),1)
 FROM NHANVIEN
 GROUP BY PHG;
 SELECT PHG,FORMAT(CONVERT(DECIMAL(15,2), AVG (LUONG),1),'N','VI_VN')
 FROM NHANVIEN
 GROUP BY PHG;
 SELECT PHG,CONVERT(VARCHAR(50),CAST( AVG (LUONG) AS money), 1)
 FROM NHANVIEN
 GROUP BY PHG;
 /*BAI2*/
 SELECT A.MADA,B.TENDEAN,
  SUM(THOIGIAN) AS 'TONG SO GIO LAM VIEC',
  CEILING(SUM(THOIGIAN)) AS 'TONG SO GIO LAM VIEC - C',
  FLOOR(SUM(THOIGIAN)) AS 'TONG SO GIO LAM VIEC - F',
  ROUND(SUM(THOIGIAN),2) AS 'TONG SO GIO LAM VIEC - R'
  FROM PHANCONG A INNER JOIN DEAN B ON A.MADA=B.MADA
  GROUP BY A.MADA,B.TENDEAN

SELECT HONV, TENLOT, TENNV, ROUND(LUONG,2) AS 'LUONG' FROM NHANVIEN WHERE LUONG>(
 SELECT ROUND(AVG(LUONG,2) FROM NHANVIEN
   WHERE PHG IN(SELECT MAPHG FROM PHONGBAN WHERE TENPHG =N'NGHIEN CUU'));

SELECT 
UPPER(HONV),
LOWER(TENLOT),TENNV,
LOWER(LEFT(TENNV,1)) +UPPER(SUBSTRING(TENNV,2,1) +LOWER(SUBSTRING(TENNV,3,LEN(TENNV))),
DCHI,
CHARINDEX(' ', DCHI),
CHARINDEX(',',dchi),
CHARINDEX(dchi,CHARINDEX(' ',DCHI)+1,CHARINDEX(',',dchi) -CHARINDEX(' ',DCHI)-1)
FROM NHANVIEN;

